### ISSUE TITLE
FB15k数据集结果

### ISSUE THREAD

**Issue by jay2012-lin** [toooooodo/RGCN-LinkPrediction#1]
请问一下，使用FB15k数据集跑出来的结果，跟原论文中的实验结果有较大差异，是代码出了什么小问题还是论文数据有误？烦请及时回复，非常感谢！

**Comment by toooooodo** [comment]
请问你跑出来的结果是多少？使用的是filter的验证方式还是raw？

**Comment by toooooodo** [comment]
我用dgl官方实现的rgcn跑了fb15k数据集，发现跑出来的结果与论文里的结果的确有差异，但我不知道这是什么原因，可能是实现的方式例如边的采样不一样。

**Comment by jay2012-lin** [comment]
好的，非常感谢！我跑出来跟原论文差的有点多。

**Comment by toooooodo** [comment]
(https://github.com/dmlc/dgl/issues/697) 也有人发现了这个问题，并在dgl的repo里提交了issue，但目前看来还没有被解决。
